title: Shuyang Gan's Homepage
page-top-title: Shuyang Gan
top-section-bg-text: International Economics
home-subtitle: Shuyang Gan&ensp;|&ensp;甘书阳
copyright-text: '&copy; Shuyang Gan 2023-2027. All Rights Reserved.'
